[providers]
    rust = "nixpacks"

[phases.setup]
    nixPkgs = ["...", "ffmpeg", "yt-dlp", "cmake", "libopus", "pkg-config", "python3"]

[phases.build]
    cmds = ["cargo build --release"]

[start]
    cmd = "./target/release/mousike-rust"
